languange: node_js

services: 
  - docker

node_js:
  - lts/*

env: 
  JWT_SECRET_KEY: ${{ secrets.JWT_SECRET_KEY }}

before_install:
  - docker-compose up -d --build

script:
  - docker exec -it fancy-todo-api_api_1 npm test
