languange: node_js

services: 
  - docker

node_js:
  - lts/*

before_script:
  - docker-compose up -d --build
  - export CONTAINER_ID=`docker ps | grep "fancy-todo-api_api_1" | awk '{ print $1 }'`

script:
  - docker start $CONTAINER_ID
  - docker exec -e TRAVIS_JOB_ID="$TRAVIS_JOB_ID" -e TRAVIS_BRANCH="$TRAVIS_BRANCH"
  - docker exec -it $CONTAINER_ID npm test
