branches:
  only:
    - master

languange: node_js

node_js:
  - node

sudo: required

services:
  - docker

before_install:
  - docker login --username $DOCKER_USERNAME --password $DOCKER_PASSWORD
  - docker build -f Dev.Dockerfile -t sundayx/fancy-todo-api:dev .
  - docker build -f Prod.Dockerfile -t sundayx/fancy-todo-api:latest .
  - docker push sundayx/fancy-todo-api:dev

install:
  - docker swarm init
  - printf $DB_NAME | docker secret create DB_NAME -
  - printf $DB_USER | docker secret create DB_USER -
  - printf $DB_PASSWORD | docker secret create DB_PASSWORD -
  - printf $JWT_ACCESS_SECRET | docker secret create JWT_ACCESS_SECRET -
  - printf $JWT_REFRESH_SECRET | docker secret create JWT_REFRESH_SECRET -
  - printf $JWT_API_KEY_SECRET | docker secret create JWT_API_KEY_SECRET -
  - printf $COOKIE_SECRET | docker secret create COOKIE_SECRET -
  - docker stack deploy --compose-file=docker-compose.test.yml fancy-todo
  - while [ "$(curl -sS 127.0.0.1:27017)" = "" ]; do echo "Retrying to connect to MongoDB..."; sleep 1; done && echo "Finished."
  - while [ "$(curl -sS 127.0.0.1:3000)" = "" ]; do echo "Retrying to connect to SmartCart API..."; sleep 1; done && echo "Finished."

script:
  - docker exec -it $(docker ps -q -f name=fancy-todo_api) yarn test

after_success:
  - docker push sundayx/fancy-todo-api:latest
