languange: node_js

services: 
  - docker

node_js:
  - lts/*

before_install:
  - docker-compose up -d --build
  - export CONTAINER_ID=`docker ps | grep "fancy-todo-api" | awk '{ print $1 }'`
  - docker ps | grep "fancy-todo-api" | awk '{ print $1 }'
  - docker ps

script:
  - docker exec -it $CONTAINER_ID npm test
