languange: node_js

services: 
  - docker

node_js:
  - lts/*

before_install:
  - docker-compose up -d --build

before_script:
  - docker-compose ps

script:
  - docker exec -it fancy-todo-api_api_1 npm test
