languange: node_js

services: 
  - docker

node_js:
  - lts/*

before_install:
  - docker-compose up -d --build
  - export API_CONTAINER_ID=`docker ps | grep "fancy-todo-api_api_1" | awk '{ print $1 }'`

before_script:
  - docker ps
  - docker images
  - docker start $API_CONTAINER_ID

script:
  - docker exec -it $API_CONTAINER_ID npm test

after_script:
  - docker-compose down
