languange: node_js

services: 
  - docker

node_js:
  - lts/*

script:
  - docker-compose up -d --build
  - docker start `docker ps | grep "fancy-todo-api_api_1" | awk '{ print $1 }'`
  - docker exec -it `docker ps | grep "fancy-todo-api_api_1" | awk '{ print $1 }'` npm test

after_script:
  - docker-compose down
