languange: node_js

services: 
  - docker

node_js:
  - lts/*

before_install:
  - docker-compose up -d --build

before_script:
  - export CONTAINER_ID=`docker ps | grep "fancy-todo-api_api" | awk '{ print $1 }'`
  - echo docker ps | grep "fancy-todo-api" | awk '{ print $1 }'

script:
  - docker exec -it $CONTAINER_ID npm test
