languange: node_js

services: 
  - docker

node_js:
  - lts/*

before_install:
  - docker-compose up -d --build

before_script:
  - export CONTAINER_ID=`docker ps | grep "fancy-todo-api_api_1" | awk '{ print $1 }'`
  - echo $$CONTAINER_ID

script:
  - docker exec -it $$CONTAINER_ID npm test
