apiVersion: apps/v1
kind: Deployment
metadata:
  name: fancy-todo-api
  labels:
    app: fancy-todo-api
spec:
  replicas: 1
  selector:
    matchLabels:
      app: fancy-todo-api
  template:
    metadata:
      labels:
        app: fancy-todo-api
    spec:
      containers:
      - name: fancy-todo-api
        image: rafiandria23/fancy-todo-api:latest
        imagePullPolicy: "Always"
        resources:
        ports:
        - containerPort: 3000
        env:
          - name: JWT_ACCESS_SECRET
            valueFrom:
              secretKeyRef:
                name: fancy-todo-api-secrets
                key: JWT_ACCESS_SECRET
          - name: JWT_REFRESH_SECRET
            valueFrom:
              secretKeyRef:
                name: fancy-todo-api-secrets
                key: JWT_REFRESH_SECRET
          - name: JWT_API_KEY_SECRET
            valueFrom:
              secretKeyRef:
                name: fancy-todo-api-secrets
                key: JWT_API_KEY_SECRET
          - name: COOKIE_SECRET
            valueFrom:
              secretKeyRef:
                name: fancy-todo-api-secrets
                key: COOKIE_SECRET
      restartPolicy: Always

