version: '3'

services: 
  mongodb:
    image: mongo:latest
    restart: always
    ports: 
      - 27017
    environment: 
      MONGO_INITDB_DATABASE: fancy-todo-api
  api:
    image: 'rafiandria23/fancy-todo-api_api:latest'
    build: 
      context: ./
      dockerfile: Dockerfile
    ports: 
      - 8080:3000
    depends_on:
      - mongodb
    links:
      - mongodb
    environment:
      NODE_ENV: production
      JWT_SECRET_KEY: $${{ secrets.JWT_SECRET_KEY }}
