version: "3.1"

services:
  mongodb:
    image: mongo:latest
    restart: always
    ports:
      - 27017:27017
    environment:
      MONGO_INITDB_DATABASE_FILE: /run/secrets/DB_NAME
      MONGO_INITDB_USERNAME_FILE: /run/secrets/DB_USER
      MONGO_INITDB_PASSWORD_FILE: /run/secrets/DB_PASSWORD
    secrets:
      - DB_NAME
      - DB_USER
      - DB_PASSWORD
    volumes:
      - mongodb-volume:/data/db

  api:
    image: sundayx/fancy-todo-api:dev
    restart: always
    ports:
      - 3000:3000
    depends_on:
      - mongodb
      - redis
    links:
      - mongodb
      - redis
    environment:
      NODE_ENV: "test"
      MONGODB_URI: "mongodb://fancy-todo_mongodb:27017"
      DB_NAME: /run/secrets/DB_NAME
      DB_USER: /run/secrets/DB_USER
      DB_PASSWORD: /run/secrets/DB_PASSWORD
      JWT_ACCESS_SECRET: /run/secrets/JWT_ACCESS_SECRET
      JWT_REFRESH_SECRET: /run/secrets/JWT_REFRESH_SECRET
      JWT_API_KEY_SECRET: /run/secrets/JWT_API_KEY_SECRET
      COOKIE_SECRET: /run/secrets/COOKIE_SECRET
    secrets:
      - DB_NAME
      - DB_USER
      - DB_PASSWORD
      - JWT_ACCESS_SECRET
      - JWT_REFRESH_SECRET
      - JWT_API_KEY_SECRET
      - COOKIE_SECRET
    volumes:
      - "./:/usr/local/app"
      - "/usr/local/app/node_modules"

secrets:
  DB_NAME:
    external: true
  DB_USER:
    external: true
  DB_PASSWORD:
    external: true
  JWT_ACCESS_SECRET:
    external: true
  JWT_REFRESH_SECRET:
    external: true
  JWT_API_KEY_SECRET:
    external: true
  COOKIE_SECRET:
    external: true

volumes:
  mongodb-volume:
