version: '3'

services: 
  fancy-todo-mongodb:
    image: mongo:latest
    restart: always
    ports: 
      - '27017'
    environment: 
      MONGO_INITDB_DATABASE: 'fancy-todo-api'
  fancy-todo-api:
    image: rafiandria23/fancy-todo-api:latest
    restart: always
    build: 
      context: ./
      dockerfile: Dockerfile
    ports: 
      - '80:3000'
    depends_on:
      - fancy-todo-mongodb
    links:
      - fancy-todo-mongodb
    environment:
      NODE_ENV: 'production'
      JWT_SECRET_KEY: $${{ secrets.JWT_SECRET_KEY }}
