version: '3'

services: 
  mongodb:
    image: mongo:latest
    restart: always
    ports: 
      - 27017
    environment: 
      MONGO_INITDB_DATABASE: 'fancy-todo-api-dev'
  api:
    build: 
      context: ./
      dockerfile: Dockerfile
    ports: 
      - 3000:3000
    depends_on:
      - mongodb
    links:
      - mongodb
    environment:
      NODE_ENV: 'development'
      JWT_SECRET_KEY: $${{ secrets.JWT_SECRET_KEY }}
      TRAVIS_JOB_ID: $$TRAVIS_JOB_ID
      TRAVIS_BRANCH: $$TRAVIS_BRANCH
