version: 2.1

workflows:
  build-and-push:
    jobs:
      - build:
          context: sundayx-default
          filters:
            branches:
              only: main

jobs:
  build:
    docker:
      - image: docker:28.5.1
    environment:
      IMAGE_NAME: sundayx/todo-api
      IMAGE_TAG: latest
    resource_class: small
    steps:
      - checkout

      - setup_remote_docker:
          version: 19.03.13

      - run:
          name: Build Docker Image
          command: docker build -t $IMAGE_NAME:$IMAGE_TAG .
